console.log("Welcome to Web 1 JavaScript");
console.log(" ");
console.log("navi here");
let name = prompt("Who are you?");
console.log("yo sup " + name);
let years = Number(prompt("how long have you lived in dunedin? "));
console.log("thats nice to hear that you have lived " + years + "  years in dunedin.");
let num1 = Number(prompt("Enter the first number"));
let num2 = Number(prompt("Enter the second number"));
console.log(num1 + num2);
let hours = Number(prompt("How many hours on average do you watch TV every night"));
console.log("So you watch " + hours * 7 + " week and " + hours * 31 + " per month and " + hours * 365 + " per month");
let age = Number(prompt("How old are you?"));
console.log("So you have lived for " + years * 365 + " days and " + years * 8766 + " hours");
let averageSpeed = Number(prompt("what is your average speed"));
let elapsedTime = Number(prompt("what is your elapsed time while driving"));
let nonTravelTime = Number(prompt("What is the non travel time "));
console.log("The distance you have traveled is " +averageSpeed * (elapsedTime - nonTravelTime)+ " KM");
let price1 = Number(prompt("first Milk price?"));
let price2 = Number(prompt("second Milk price?"));
let price3 = Number(prompt("third Milk price?"));
console.log("so the average of all the milks is " + ((price1+price2+price3)/3).toFixed(2));
